// Clean-room metadata mapping: GGG metadata paths <-> poe.ninja ids.
// Provenance: the bulk of the mapping is AUTO-GENERATED by
// scripts/generate-mapping.ts, which cross-validates every GGG path against the
// poe.ninja PoE2 economy overview rate using real completed-hour fixture data.
// Entries that fail cross-validation stay quarantined and are never guessed.
//
// Manually curated entries below (hub currencies) were additionally verified
// against the live GGG feed + poe.ninja on 2026-08-18:
//   chaos->divine GGG 0.1056 vs ninja 0.1009  (5% match)
//   chaos->exalted GGG 33.5  vs ninja 33.45  (0.2% match)
//   mirror->divine GGG 4758  vs ninja 4759   (0.02% match)

import type { ItemId } from "./types.ts";
import { GENERATED_MAPPING, AUTHORITATIVE_IDENTITY_MAPPING } from "./mapping.generated.ts";

export const GGG_HUB_PATHS = {
  DIVINE: "Metadata/Items/Currency/CurrencyModValues",
  EXALTED: "Metadata/Items/Currency/CurrencyAddModToRare",
  CHAOS: "Metadata/Items/Currency/CurrencyRerollRare",
} as const;

const verified = "checked-in-verified" as const;

// Public PoE2 wiki Currency Exchange table, checked 2026-08-20.
// Fees are per unit received on the I WANT side.
// https://www.poe2wiki.net/wiki/Currency_exchange
const VERIFIED_GOLD_BY_NAME: Record<string, number> = {
  "Orb of Annulment": 1000,
  "Artificer's Shard": 100,
  "Glassblower's Bauble": 750,
  "Lesser Jeweller's Orb": 200,
  "Greater Jeweller's Orb": 600,
  "Perfect Jeweller's Orb": 1000,
  "Orb of Chance": 1000,
  "Vaal Orb": 160,
  "Arcanist's Etcher": 500,
  "Blacksmith's Whetstone": 500,
};

const ESTIMATED_GOLD_BY_CATEGORY: Record<string, number> = {
  Currency: 1000,
  Breach: 250,
  Ritual: 500,
  Vaal: 1000,
  Expedition: 1000,
  SoulCore: 1000,
  Gem: 9000,
};

/** Manually curated entries (merged over generated ones for gold-cost fixes). */
const MANUAL_OVERRIDES: Record<string, ItemId> = {
  [GGG_HUB_PATHS.DIVINE]: {
    gggPath: GGG_HUB_PATHS.DIVINE,
    ninjaId: "divine",
    displayName: "Divine Orb",
    category: "Currency",
    iconUrl: null,
    goldCostPerUnit: 800,
    mappingSource: verified,
    lastVerifiedUtc: "2026-08-18T00:00:00Z",
  },
  [GGG_HUB_PATHS.EXALTED]: {
    gggPath: GGG_HUB_PATHS.EXALTED,
    ninjaId: "exalted",
    displayName: "Exalted Orb",
    category: "Currency",
    iconUrl: null,
    goldCostPerUnit: 120,
    mappingSource: verified,
    lastVerifiedUtc: "2026-08-18T00:00:00Z",
  },
  [GGG_HUB_PATHS.CHAOS]: {
    gggPath: GGG_HUB_PATHS.CHAOS,
    ninjaId: "chaos",
    displayName: "Chaos Orb",
    category: "Currency",
    iconUrl: null,
    goldCostPerUnit: 160,
    mappingSource: verified,
    lastVerifiedUtc: "2026-08-18T00:00:00Z",
  },
};

export const ITEM_MAP: Record<string, ItemId> = Object.fromEntries(
  Object.entries(GENERATED_MAPPING).map(([path, rec]) => [path, { ...rec.entry, mappingSource: verified }]),
);

// Merge authoritative identity-only entries (real GGG path + readable name +
// icon from the poe.ninja image-decoded bridge) so `lookupItem` resolves them.
// These carry goldCostPerUnit = -1 (FEE_UNKNOWN): they render a readable
// identity, but goldCostPerUnit() reports unverified so no route is marketed
// or priced without a verified fee. Ambiguous paths are never included.
for (const [path, rec] of Object.entries(AUTHORITATIVE_IDENTITY_MAPPING)) {
  if (ITEM_MAP[path]) continue; // rate-verified entry wins over identity-only
  ITEM_MAP[path] = { ...rec.entry, mappingSource: verified };
}

for (const item of Object.values(ITEM_MAP)) {
  const fee = VERIFIED_GOLD_BY_NAME[item.displayName];
  if (fee !== undefined) item.goldCostPerUnit = fee;
}

// Apply manual overrides (gold costs from the poe2wiki exchange table).
for (const [path, item] of Object.entries(MANUAL_OVERRIDES)) {
  ITEM_MAP[path] = item;
}

export function lookupItem(gggPath: string): ItemId | null {
  return ITEM_MAP[gggPath] ?? null;
}

export function displayName(gggPath: string): string {
  return lookupItem(gggPath)?.displayName ?? gggPath.split("/").pop() ?? gggPath;
}

/**
 * Gold cost per received unit. If unmapped OR the fee is unverified (-1),
 * returns 0 and flags `verified: false` so the caller drops the route or marks
 * it low-confidence — never guess a fee, never treat an unknown fee as zero.
 */
export function goldCostPerUnit(gggPath: string): { cost: number; verified: boolean } {
  const item = lookupItem(gggPath);
  if (!item || item.mappingSource !== "checked-in-verified" || item.goldCostPerUnit < 0) {
    return { cost: 0, verified: false };
  }
  return { cost: item.goldCostPerUnit, verified: true };
}

/** Product-only fallback for research signals; it remains explicitly unverified. */
export function estimatedGoldCostPerUnit(gggPath: string): { cost: number; verified: boolean; basis: string } {
  const exact = goldCostPerUnit(gggPath);
  if (exact.verified) return { ...exact, basis: "verified item fee" };
  const item = lookupItem(gggPath);
  const category = item?.category ?? "unmapped item";
  const cost = ESTIMATED_GOLD_BY_CATEGORY[category] ?? 1000;
  return { cost, verified: false, basis: `${category} fallback: ${cost.toLocaleString("en-US")} gold per unit received` };
}
