// GENERATED by scripts/generate-ninja-bridge.ts — do not edit by hand.
//
// Identity established from the poe.ninja art file, then confirmed by two
// independent Divine prices (GGG completed hour vs poe.ninja) agreeing within
// 25%. Ambiguous art leaves and price disagreements are quarantined,
// never guessed.
//
// Source hour : 2026-08-21T01:00:00.000Z
// Accepted    : 24 (4 not already in the checked-in map)
// Quarantined : 18
//
// goldCostPerUnit is deliberately -1 (FEE_UNKNOWN): poe.ninja does not publish
// Currency Exchange gold fees, so these items render a readable identity and a
// price, and remain excluded from any fee-verified claim.

import type { ItemId } from "./types.ts";

export interface NinjaBridgeEntry {
  entry: ItemId;
  ninjaId: string;
  /** Divine price from each source at generation time, and their gap. */
  gggDivine: number;
  ninjaDivine: number;
  deviationPct: number;
}

export const NINJA_BRIDGE_MAPPING: Record<string, NinjaBridgeEntry> = {
  "Metadata/Items/Currency/CurrencyAddEquipmentSocket": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyAddEquipmentSocket",
      ninjaId: "artificers",
      displayName: "Artificer's Orb",
      category: "Currency",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lBZGRFcXVpcG1lbnRTb2NrZXQiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/5131fd4774/CurrencyAddEquipmentSocket.png",
      goldCostPerUnit: -1,
      mappingSource: "poe-ninja",
      lastVerifiedUtc: "2026-08-21T01:00:00.000Z",
    },
    ninjaId: "artificers",
    gggDivine: 0.005,
    ninjaDivine: 0.005,
    deviationPct: 0,
  },
  "Metadata/Items/Currency/CurrencyArmourQuality": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyArmourQuality",
      ninjaId: "scrap",
      displayName: "Armourer's Scrap",
      category: "Currency",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lBcm1vdXJRdWFsaXR5Iiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/d5868f596d/CurrencyArmourQuality.png",
      goldCostPerUnit: -1,
      mappingSource: "poe-ninja",
      lastVerifiedUtc: "2026-08-21T01:00:00.000Z",
    },
    ninjaId: "scrap",
    gggDivine: 0.0025673940949935813,
    ninjaDivine: 0.003043,
    deviationPct: 15.63,
  },
  "Metadata/Items/Currency/CurrencyBreachShard": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyBreachShard",
      ninjaId: "breach-splinter",
      displayName: "Breach Splinter",
      category: "Breach",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQnJlYWNoL0JyZWFjaHN0b25lU3BsaW50ZXIiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/4abb17ea8e/BreachstoneSplinter.png",
      goldCostPerUnit: -1,
      mappingSource: "poe-ninja",
      lastVerifiedUtc: "2026-08-21T01:00:00.000Z",
    },
    ninjaId: "breach-splinter",
    gggDivine: 0.0006666666666666666,
    ninjaDivine: 0.000692,
    deviationPct: 3.66,
  },
  "Metadata/Items/Currency/CurrencyCorrupt": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyCorrupt",
      ninjaId: "vaal",
      displayName: "Vaal Orb",
      category: "Currency",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lWYWFsIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/72bc84396c/CurrencyVaal.png",
      goldCostPerUnit: -1,
      mappingSource: "poe-ninja",
      lastVerifiedUtc: "2026-08-21T01:00:00.000Z",
    },
    ninjaId: "vaal",
    gggDivine: 0.007860209202491081,
    ninjaDivine: 0.00772,
    deviationPct: 1.78,
  },
  "Metadata/Items/Currency/CurrencyDuplicate": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyDuplicate",
      ninjaId: "mirror",
      displayName: "Mirror of Kalandra",
      category: "Currency",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lEdXBsaWNhdGUiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/26bc31680e/CurrencyDuplicate.png",
      goldCostPerUnit: -1,
      mappingSource: "poe-ninja",
      lastVerifiedUtc: "2026-08-21T01:00:00.000Z",
    },
    ninjaId: "mirror",
    gggDivine: 4845,
    ninjaDivine: 4824,
    deviationPct: 0.43,
  },
  "Metadata/Items/Currency/CurrencyModValues": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyModValues",
      ninjaId: "divine",
      displayName: "Divine Orb",
      category: "Currency",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lNb2RWYWx1ZXMiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/2986e220b3/CurrencyModValues.png",
      goldCostPerUnit: -1,
      mappingSource: "poe-ninja",
      lastVerifiedUtc: "2026-08-21T01:00:00.000Z",
    },
    ninjaId: "divine",
    gggDivine: 1,
    ninjaDivine: 1,
    deviationPct: 0,
  },
  "Metadata/Items/Currency/CurrencyRemoveMod": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyRemoveMod",
      ninjaId: "annul",
      displayName: "Orb of Annulment",
      category: "Currency",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQW5udWxsT3JiIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/2daba8ccca/AnnullOrb.png",
      goldCostPerUnit: -1,
      mappingSource: "poe-ninja",
      lastVerifiedUtc: "2026-08-21T01:00:00.000Z",
    },
    ninjaId: "annul",
    gggDivine: 0.4,
    ninjaDivine: 0.4371,
    deviationPct: 8.49,
  },
  "Metadata/Items/Currency/CurrencyUpgradeRandomly": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyUpgradeRandomly",
      ninjaId: "chance",
      displayName: "Orb of Chance",
      category: "Currency",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lVcGdyYWRlVG9VbmlxdWUiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/93c6cc8d5b/CurrencyUpgradeToUnique.png",
      goldCostPerUnit: -1,
      mappingSource: "poe-ninja",
      lastVerifiedUtc: "2026-08-21T01:00:00.000Z",
    },
    ninjaId: "chance",
    gggDivine: 0.013071895424836602,
    ninjaDivine: 0.01495,
    deviationPct: 12.56,
  },
  "Metadata/Items/Currency/OmenOnAbyssRerollOptions": {
    entry: {
      gggPath: "Metadata/Items/Currency/OmenOnAbyssRerollOptions",
      ninjaId: "omen-of-abyssal-echoes",
      displayName: "Omen of Abyssal Echoes",
      category: "Ritual",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvT21lbnMvT21lbk9uQWJ5c3NSZXJvbGxPcHRpb25zIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/9690f99016/OmenOnAbyssRerollOptions.png",
      goldCostPerUnit: -1,
      mappingSource: "poe-ninja",
      lastVerifiedUtc: "2026-08-21T01:00:00.000Z",
    },
    ninjaId: "omen-of-abyssal-echoes",
    gggDivine: 0.11764705882352941,
    ninjaDivine: 0.1299,
    deviationPct: 9.43,
  },
  "Metadata/Items/Currency/OmenOnAnnulRemoveAbyssMod": {
    entry: {
      gggPath: "Metadata/Items/Currency/OmenOnAnnulRemoveAbyssMod",
      ninjaId: "omen-of-light",
      displayName: "Omen of Light",
      category: "Ritual",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvT21lbnMvT21lbk9uQW5udWxSZW1vdmVBYnlzc01vZCIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/eb39bcb3d7/OmenOnAnnulRemoveAbyssMod.png",
      goldCostPerUnit: -1,
      mappingSource: "poe-ninja",
      lastVerifiedUtc: "2026-08-21T01:00:00.000Z",
    },
    ninjaId: "omen-of-light",
    gggDivine: 8.470588235294118,
    ninjaDivine: 8.36,
    deviationPct: 1.31,
  },
  "Metadata/Items/Currency/OmenOnChanceNotDestroy": {
    entry: {
      gggPath: "Metadata/Items/Currency/OmenOnChanceNotDestroy",
      ninjaId: "omen-of-chance",
      displayName: "Omen of Chance",
      category: "Ritual",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvT21lbnMvT21lbk9uQ2hhbmNlTm90RGVzdHJveSIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/461b794959/OmenOnChanceNotDestroy.png",
      goldCostPerUnit: -1,
      mappingSource: "poe-ninja",
      lastVerifiedUtc: "2026-08-21T01:00:00.000Z",
    },
    ninjaId: "omen-of-chance",
    gggDivine: 15.354838709677422,
    ninjaDivine: 15.34,
    deviationPct: 0.1,
  },
  "Metadata/Items/Currency/OmenOnChaosMapItemRarity": {
    entry: {
      gggPath: "Metadata/Items/Currency/OmenOnChaosMapItemRarity",
      ninjaId: "omen-of-chaotic-rarity",
      displayName: "Omen of Chaotic Rarity",
      category: "Ritual",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvT21lbnMvT21lbk9uQ2hhb3NNYXBJdGVtUmFyaXR5Iiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/e7d9f8657d/OmenOnChaosMapItemRarity.png",
      goldCostPerUnit: -1,
      mappingSource: "poe-ninja",
      lastVerifiedUtc: "2026-08-21T01:00:00.000Z",
    },
    ninjaId: "omen-of-chaotic-rarity",
    gggDivine: 0.375,
    ninjaDivine: 0.3426,
    deviationPct: 8.64,
  },
  "Metadata/Items/Currency/OmenOnChaosMapMonsterEffectiveness": {
    entry: {
      gggPath: "Metadata/Items/Currency/OmenOnChaosMapMonsterEffectiveness",
      ninjaId: "omen-of-chaotic-effectiveness",
      displayName: "Omen of Chaotic Effectiveness",
      category: "Ritual",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvT21lbnMvT21lbk9uQ2hhb3NNYXBNb25zdGVyRWZmZWN0aXZlbmVzcyIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/1dc9f3dea9/OmenOnChaosMapMonsterEffectiveness.png",
      goldCostPerUnit: -1,
      mappingSource: "poe-ninja",
      lastVerifiedUtc: "2026-08-21T01:00:00.000Z",
    },
    ninjaId: "omen-of-chaotic-effectiveness",
    gggDivine: 0.054945054945054944,
    ninjaDivine: 0.06413,
    deviationPct: 14.32,
  },
  "Metadata/Items/Currency/OmenOnChaosMapPackSize": {
    entry: {
      gggPath: "Metadata/Items/Currency/OmenOnChaosMapPackSize",
      ninjaId: "omen-of-chaotic-quantity",
      displayName: "Omen of Chaotic Quantity",
      category: "Ritual",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvT21lbnMvT21lbk9uQ2hhb3NNYXBQYWNrU2l6ZSIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/9ea6c86009/OmenOnChaosMapPackSize.png",
      goldCostPerUnit: -1,
      mappingSource: "poe-ninja",
      lastVerifiedUtc: "2026-08-21T01:00:00.000Z",
    },
    ninjaId: "omen-of-chaotic-quantity",
    gggDivine: 0.2857142857142857,
    ninjaDivine: 0.3148,
    deviationPct: 9.24,
  },
  "Metadata/Items/Currency/OmenOnDivineSanctify": {
    entry: {
      gggPath: "Metadata/Items/Currency/OmenOnDivineSanctify",
      ninjaId: "omen-of-sanctification",
      displayName: "Omen of Sanctification",
      category: "Ritual",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvT21lbnMvT21lbk9uRGl2aW5lU2FuY3RpZnkiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/895416b2b9/OmenOnDivineSanctify.png",
      goldCostPerUnit: -1,
      mappingSource: "poe-ninja",
      lastVerifiedUtc: "2026-08-21T01:00:00.000Z",
    },
    ninjaId: "omen-of-sanctification",
    gggDivine: 0.75,
    ninjaDivine: 0.605,
    deviationPct: 19.33,
  },
  "Metadata/Items/Currency/OmenOnPerfectEssencePrefix": {
    entry: {
      gggPath: "Metadata/Items/Currency/OmenOnPerfectEssencePrefix",
      ninjaId: "omen-of-sinistral-crystallisation",
      displayName: "Omen of Sinistral Crystallisation",
      category: "Ritual",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvT21lbnMvT21lbk9uUGVyZmVjdEVzc2VuY2VQcmVmaXgiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/75263d6201/OmenOnPerfectEssencePrefix.png",
      goldCostPerUnit: -1,
      mappingSource: "poe-ninja",
      lastVerifiedUtc: "2026-08-21T01:00:00.000Z",
    },
    ninjaId: "omen-of-sinistral-crystallisation",
    gggDivine: 0.15384615384615385,
    ninjaDivine: 0.1588,
    deviationPct: 3.12,
  },
  "Metadata/Items/Currency/OmenOnPerfectEssenceSuffix": {
    entry: {
      gggPath: "Metadata/Items/Currency/OmenOnPerfectEssenceSuffix",
      ninjaId: "omen-of-dextral-crystallisation",
      displayName: "Omen of Dextral Crystallisation",
      category: "Ritual",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvT21lbnMvT21lbk9uUGVyZmVjdEVzc2VuY2VTdWZmaXgiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/7ec019819e/OmenOnPerfectEssenceSuffix.png",
      goldCostPerUnit: -1,
      mappingSource: "poe-ninja",
      lastVerifiedUtc: "2026-08-21T01:00:00.000Z",
    },
    ninjaId: "omen-of-dextral-crystallisation",
    gggDivine: 0.3076923076923077,
    ninjaDivine: 0.359,
    deviationPct: 14.29,
  },
  "Metadata/Items/Currency/OmenSellVendorRandomise": {
    entry: {
      gggPath: "Metadata/Items/Currency/OmenSellVendorRandomise",
      ninjaId: "omen-of-bartering",
      displayName: "Omen of Bartering",
      category: "Ritual",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvT21lbnMvT21lblNlbGxWZW5kb3JSYW5kb21pc2UiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/12ef99da8b/OmenSellVendorRandomise.png",
      goldCostPerUnit: -1,
      mappingSource: "poe-ninja",
      lastVerifiedUtc: "2026-08-21T01:00:00.000Z",
    },
    ninjaId: "omen-of-bartering",
    gggDivine: 0.04777777777777778,
    ninjaDivine: 0.04551,
    deviationPct: 4.75,
  },
  "Metadata/Items/SoulCores/AmanamusGaze": {
    entry: {
      gggPath: "Metadata/Items/SoulCores/AmanamusGaze",
      ninjaId: "amanamus-gaze",
      displayName: "Amanamu's Gaze",
      category: "Abyss",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQWJ5c3NhbEV5ZVNvY2tldGFibGVzL0FtYW5hbXVzR2F6ZSIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/53ba66a7d4/AmanamusGaze.png",
      goldCostPerUnit: -1,
      mappingSource: "poe-ninja",
      lastVerifiedUtc: "2026-08-21T01:00:00.000Z",
    },
    ninjaId: "amanamus-gaze",
    gggDivine: 0.1446808510638298,
    ninjaDivine: 0.1508,
    deviationPct: 4.06,
  },
  "Metadata/Items/SoulCores/KurgalsGaze": {
    entry: {
      gggPath: "Metadata/Items/SoulCores/KurgalsGaze",
      ninjaId: "kurgals-gaze",
      displayName: "Kurgal's Gaze",
      category: "Abyss",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQWJ5c3NhbEV5ZVNvY2tldGFibGVzL0t1cmdhbHNHYXplIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/c21eb07bab/KurgalsGaze.png",
      goldCostPerUnit: -1,
      mappingSource: "poe-ninja",
      lastVerifiedUtc: "2026-08-21T01:00:00.000Z",
    },
    ninjaId: "kurgals-gaze",
    gggDivine: 40.5,
    ninjaDivine: 39.53,
    deviationPct: 2.4,
  },
  "Metadata/Items/SoulCores/TecrodsGaze": {
    entry: {
      gggPath: "Metadata/Items/SoulCores/TecrodsGaze",
      ninjaId: "tecrods-gaze",
      displayName: "Tecrod's Gaze",
      category: "Abyss",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQWJ5c3NhbEV5ZVNvY2tldGFibGVzL1RlY3JvZHNHYXplIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/ef2a9355b4/TecrodsGaze.png",
      goldCostPerUnit: -1,
      mappingSource: "poe-ninja",
      lastVerifiedUtc: "2026-08-21T01:00:00.000Z",
    },
    ninjaId: "tecrods-gaze",
    gggDivine: 8.470588235294118,
    ninjaDivine: 8.52,
    deviationPct: 0.58,
  },
  "Metadata/Items/Ultimatum/TrialmasterKey1": {
    entry: {
      gggPath: "Metadata/Items/Ultimatum/TrialmasterKey1",
      ninjaId: "cowardly-fate",
      displayName: "Cowardly Fate",
      category: "Fragments",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU291bENvcmVzL1RyaWFsbWFzdGVyS2V5MSIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/661ab60074/TrialmasterKey1.png",
      goldCostPerUnit: -1,
      mappingSource: "poe-ninja",
      lastVerifiedUtc: "2026-08-21T01:00:00.000Z",
    },
    ninjaId: "cowardly-fate",
    gggDivine: 7.466666666666667,
    ninjaDivine: 7.9,
    deviationPct: 5.49,
  },
  "Metadata/Items/Ultimatum/TrialmasterKey2": {
    entry: {
      gggPath: "Metadata/Items/Ultimatum/TrialmasterKey2",
      ninjaId: "deadly-fate",
      displayName: "Deadly Fate",
      category: "Fragments",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU291bENvcmVzL1RyaWFsbWFzdGVyS2V5MiIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/cccae44832/TrialmasterKey2.png",
      goldCostPerUnit: -1,
      mappingSource: "poe-ninja",
      lastVerifiedUtc: "2026-08-21T01:00:00.000Z",
    },
    ninjaId: "deadly-fate",
    gggDivine: 8.470588235294118,
    ninjaDivine: 7.66,
    deviationPct: 9.57,
  },
  "Metadata/Items/Ultimatum/TrialmasterKey3": {
    entry: {
      gggPath: "Metadata/Items/Ultimatum/TrialmasterKey3",
      ninjaId: "victorious-fate",
      displayName: "Victorious Fate",
      category: "Fragments",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU291bENvcmVzL1RyaWFsbWFzdGVyS2V5MyIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/0270951a73/TrialmasterKey3.png",
      goldCostPerUnit: -1,
      mappingSource: "poe-ninja",
      lastVerifiedUtc: "2026-08-21T01:00:00.000Z",
    },
    ninjaId: "victorious-fate",
    gggDivine: 7.666666666666667,
    ninjaDivine: 7.81,
    deviationPct: 1.84,
  },
};

/** Paths rejected at generation time, kept so the exclusion is auditable. */
export const NINJA_BRIDGE_QUARANTINE: Array<{ path: string; reason: string }> = [
  {
    "path": "Metadata/Items/Currency/CurrencyAddModToMagic",
    "reason": "ambiguous art leaf (3 poe.ninja lines)"
  },
  {
    "path": "Metadata/Items/Currency/CurrencyAddModToRare",
    "reason": "ambiguous art leaf (3 poe.ninja lines)"
  },
  {
    "path": "Metadata/Items/Currency/CurrencyFlaskQuality",
    "reason": "price disagreement 46.6% > 25%"
  },
  {
    "path": "Metadata/Items/Currency/CurrencyGemQuality",
    "reason": "price disagreement 76.4% > 25%"
  },
  {
    "path": "Metadata/Items/Currency/CurrencyIdentification",
    "reason": "price disagreement 53.7% > 25%"
  },
  {
    "path": "Metadata/Items/Currency/CurrencyRerollRare",
    "reason": "ambiguous art leaf (3 poe.ninja lines)"
  },
  {
    "path": "Metadata/Items/Currency/CurrencyUpgradeMagicToRare",
    "reason": "ambiguous art leaf (3 poe.ninja lines)"
  },
  {
    "path": "Metadata/Items/Currency/CurrencyUpgradeToMagic",
    "reason": "ambiguous art leaf (3 poe.ninja lines)"
  },
  {
    "path": "Metadata/Items/Currency/CurrencyUpgradeToRare",
    "reason": "price disagreement 30.5% > 25%"
  },
  {
    "path": "Metadata/Items/Currency/CurrencyWeaponQuality",
    "reason": "price disagreement 80.5% > 25%"
  },
  {
    "path": "Metadata/Items/Currency/OmenGambleNoGoldCost",
    "reason": "no GGG Divine price this hour"
  },
  {
    "path": "Metadata/Items/Currency/OmenOnAbyssAddPrefixes",
    "reason": "price disagreement 79.9% > 25%"
  },
  {
    "path": "Metadata/Items/Currency/OmenOnAbyssAddSuffixes",
    "reason": "price disagreement 56.6% > 25%"
  },
  {
    "path": "Metadata/Items/Currency/OmenOnAbyssVeilAllAndCorrupt",
    "reason": "price disagreement 68.0% > 25%"
  },
  {
    "path": "Metadata/Items/Currency/OmenOnChanceAncientOrb",
    "reason": "price disagreement 41.6% > 25%"
  },
  {
    "path": "Metadata/Items/Currency/OmenOnDivineRerollImplicits",
    "reason": "price disagreement 26.1% > 25%"
  },
  {
    "path": "Metadata/Items/Currency/OmenOnExaltConsumeQuality",
    "reason": "price disagreement 70.9% > 25%"
  },
  {
    "path": "Metadata/Items/SoulCores/UlamansGaze",
    "reason": "price disagreement 43.0% > 25%"
  }
];
