// AUTO-GENERATED. Do not edit by hand — run `npx tsx scripts/generate-mapping.ts`.
// Provenance: cross-validated 2026-08-18 against GGG completed-hour feed
// (1787022000, league 'Runes of Aldur') and poe.ninja PoE2 economy overview.
// Verified entries matched within 25% of the poe.ninja implied rate across all
// observed markets. Quarantined entries failed the check and are NOT added.
import type { ItemId } from "./types";

export interface MappingRecord {
  entry: ItemId;
  /** implied divine rate from poe.ninja used for validation */
  validatedRate: number;
  /** number of independent market observations used */
  observations: number;
}

export const GENERATED_MAPPING: Record<string, MappingRecord> = {
  "Metadata/Items/Currency/CurrencyModValues": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyModValues",
      ninjaId: "divine",
      displayName: "Divine Orb",
      category: "Currency",
      iconUrl: "/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lNb2RWYWx1ZXMiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/2986e220b3/CurrencyModValues.png",
      goldCostPerUnit: 800,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 1,
    observations: 23,
  },
  "Metadata/Items/Currency/CurrencyAddModToRare": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyAddModToRare",
      ninjaId: "exalted",
      displayName: "Exalted Orb",
      category: "Currency",
      iconUrl: "/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lBZGRNb2RUb1JhcmUiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/ad7c366789/CurrencyAddModToRare.png",
      goldCostPerUnit: 120,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0.003016,
    observations: 22,
  },
  "Metadata/Items/Currency/CurrencyRerollRare": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyRerollRare",
      ninjaId: "chaos",
      displayName: "Chaos Orb",
      category: "Currency",
      iconUrl: "/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lSZXJvbGxSYXJlIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/c0ca392a78/CurrencyRerollRare.png",
      goldCostPerUnit: 160,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0.1009,
    observations: 21,
  },
  "Metadata/Items/Currency/CurrencyRerollRare2": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyRerollRare2",
      ninjaId: "greater-chaos-orb",
      displayName: "Greater Chaos Orb",
      category: "Currency",
      iconUrl: "/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lSZXJvbGxSYXJlIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/c0ca392a78/CurrencyRerollRare.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0.2961,
    observations: 6,
  },
  "Metadata/Items/Currency/CurrencyUpgradeToMagic": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyUpgradeToMagic",
      ninjaId: "transmute",
      displayName: "Orb of Transmutation",
      category: "Currency",
      iconUrl: "/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lVcGdyYWRlVG9NYWdpYyIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/2f8e1ff9f8/CurrencyUpgradeToMagic.png",
      goldCostPerUnit: 50,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0.0004293,
    observations: 4,
  },
  "Metadata/Items/Currency/CurrencyGemQuality": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyGemQuality",
      ninjaId: "gcp",
      displayName: "Gemcutter's Prism",
      category: "Currency",
      iconUrl: "/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lHZW1RdWFsaXR5Iiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/f4bace18d7/CurrencyGemQuality.png",
      goldCostPerUnit: 1000,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0.01799,
    observations: 4,
  },
  "Metadata/Items/Currency/CurrencyAddModToRare2": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyAddModToRare2",
      ninjaId: "greater-exalted-orb",
      displayName: "Greater Exalted Orb",
      category: "Currency",
      iconUrl: "/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lBZGRNb2RUb1JhcmUiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/ad7c366789/CurrencyAddModToRare.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0.01336,
    observations: 4,
  },
  "Metadata/Items/Currency/CurrencyAddModToRare3": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyAddModToRare3",
      ninjaId: "perfect-exalted-orb",
      displayName: "Perfect Exalted Orb",
      category: "Currency",
      iconUrl: "/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lBZGRNb2RUb1JhcmUiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/ad7c366789/CurrencyAddModToRare.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 2.23,
    observations: 4,
  },
  "Metadata/Items/Currency/CurrencyIdentification": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyIdentification",
      ninjaId: "wisdom",
      displayName: "Scroll of Wisdom",
      category: "Currency",
      iconUrl: "/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lJZGVudGlmaWNhdGlvbiIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/884f7bc58b/CurrencyIdentification.png",
      goldCostPerUnit: 1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0.00008,
    observations: 3,
  },
  "Metadata/Items/Currency/CurrencyAddModToMagic": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyAddModToMagic",
      ninjaId: "aug",
      displayName: "Orb of Augmentation",
      category: "Currency",
      iconUrl: "/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lBZGRNb2RUb01hZ2ljIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/c8ad0ddc84/CurrencyAddModToMagic.png",
      goldCostPerUnit: 200,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0.0004197,
    observations: 3,
  },
  "Metadata/Items/Currency/CurrencyUpgradeToRare": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyUpgradeToRare",
      ninjaId: "alch",
      displayName: "Orb of Alchemy",
      category: "Currency",
      iconUrl: "/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lVcGdyYWRlVG9SYXJlIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/9b80b44821/CurrencyUpgradeToRare.png",
      goldCostPerUnit: 200,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0.001989,
    observations: 3,
  },
  "Metadata/Items/Currency/CurrencyArmourQuality": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyArmourQuality",
      ninjaId: "scrap",
      displayName: "Armourer's Scrap",
      category: "Currency",
      iconUrl: "/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lBcm1vdXJRdWFsaXR5Iiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/d5868f596d/CurrencyArmourQuality.png",
      goldCostPerUnit: 250,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0.004055,
    observations: 3,
  },
  "Metadata/Items/Currency/CurrencyAddEquipmentSocket": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyAddEquipmentSocket",
      ninjaId: "artificers",
      displayName: "Artificer's Orb",
      category: "Currency",
      iconUrl: "/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lBZGRFcXVpcG1lbnRTb2NrZXQiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/5131fd4774/CurrencyAddEquipmentSocket.png",
      goldCostPerUnit: 1000,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0.001558,
    observations: 3,
  },
  "Metadata/Items/Currency/CurrencyRerollRare3": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyRerollRare3",
      ninjaId: "perfect-chaos-orb",
      displayName: "Perfect Chaos Orb",
      category: "Currency",
      iconUrl: "/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lSZXJvbGxSYXJlIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/c0ca392a78/CurrencyRerollRare.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 4.89,
    observations: 3,
  },
  "Metadata/Items/Currency/CurrencyAddModToMagic3": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyAddModToMagic3",
      ninjaId: "perfect-orb-of-augmentation",
      displayName: "Perfect Orb of Augmentation",
      category: "Currency",
      iconUrl: "/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lBZGRNb2RUb01hZ2ljIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/c8ad0ddc84/CurrencyAddModToMagic.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0.08836,
    observations: 3,
  },
  "Metadata/Items/Currency/CurrencyUpgradeToMagic3": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyUpgradeToMagic3",
      ninjaId: "perfect-orb-of-transmutation",
      displayName: "Perfect Orb of Transmutation",
      category: "Currency",
      iconUrl: "/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lVcGdyYWRlVG9NYWdpYyIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/2f8e1ff9f8/CurrencyUpgradeToMagic.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0.01319,
    observations: 3,
  },
  "Metadata/Items/Currency/CurrencyUpgradeMagicToRare2": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyUpgradeMagicToRare2",
      ninjaId: "greater-regal-orb",
      displayName: "Greater Regal Orb",
      category: "Currency",
      iconUrl: "/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lVcGdyYWRlTWFnaWNUb1JhcmUiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/e8fb148e80/CurrencyUpgradeMagicToRare.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0.01388,
    observations: 3,
  },
  "Metadata/Items/Currency/CurrencyUpgradeMagicToRare3": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyUpgradeMagicToRare3",
      ninjaId: "perfect-regal-orb",
      displayName: "Perfect Regal Orb",
      category: "Currency",
      iconUrl: "/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lVcGdyYWRlTWFnaWNUb1JhcmUiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/e8fb148e80/CurrencyUpgradeMagicToRare.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0.05455,
    observations: 3,
  },
  "Metadata/Items/Currency/CurrencyDuplicate": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyDuplicate",
      ninjaId: "mirror",
      displayName: "Mirror of Kalandra",
      category: "Currency",
      iconUrl: "/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lEdXBsaWNhdGUiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/26bc31680e/CurrencyDuplicate.png",
      goldCostPerUnit: 25000,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 4759,
    observations: 1,
  },
  "Metadata/Items/Currency/CurrencyHinekorasLock": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyHinekorasLock",
      ninjaId: "hinekoras-lock",
      displayName: "Hinekora's Lock",
      category: "Currency",
      iconUrl: "/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvSGluZWtvcmFzTG9jayIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/ab2163ae06/HinekorasLock.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 1139,
    observations: 1,
  },
};

export const QUARANTINED_MAPPING: Record<string, { ninjaId: string; reason: string }> = {
  "Metadata/Items/Currency/CurrencyWeaponQuality": { ninjaId: "whetstone", reason: "failed cross-validation" },
  "Metadata/Items/Currency/CurrencyUpgradeMagicToRare": { ninjaId: "regal", reason: "failed cross-validation" },
  "Metadata/Items/Currency/CurrencyUpgradeToUnique": { ninjaId: "chance", reason: "failed cross-validation" },
  "Metadata/Items/Currency/CurrencyFlaskQuality": { ninjaId: "bauble", reason: "failed cross-validation" },
  "Metadata/Items/Currency/CurrencyVaal": { ninjaId: "vaal", reason: "failed cross-validation" },
  "Metadata/Items/Currency/CurrencyRerollSocketNumbers01": { ninjaId: "lesser-jewellers-orb", reason: "failed cross-validation" },
  "Metadata/Items/Currency/CurrencyRerollSocketNumbers02": { ninjaId: "greater-jewellers-orb", reason: "failed cross-validation" },
  "Metadata/Items/Currency/CurrencyRerollSocketNumbers03": { ninjaId: "perfect-jewellers-orb", reason: "failed cross-validation" },
  "Metadata/Items/Currency/AnnullOrb": { ninjaId: "annul", reason: "failed cross-validation" },
  "Metadata/Items/Currency/FracturingOrb": { ninjaId: "fracturing-orb", reason: "failed cross-validation" },
  "Metadata/Items/Currency/StrongboxSkeletonKey": { ninjaId: "cryptic-key", reason: "failed cross-validation" },
  "Metadata/Items/Currency/CurrencyAddModToMagic2": { ninjaId: "greater-orb-of-augmentation", reason: "failed cross-validation" },
  "Metadata/Items/Currency/CurrencyUpgradeToMagic2": { ninjaId: "greater-orb-of-transmutation", reason: "failed cross-validation" },
};