// Clean-room metadata mapping: GGG metadata paths <-> poe.ninja ids.
// Provenance: the bulk of the mapping is AUTO-GENERATED by
// scripts/generate-mapping.ts, which cross-validates every GGG path against the
// poe.ninja PoE2 economy overview rate using real completed-hour fixture data.
// Entries that fail cross-validation stay quarantined and are never guessed.
//
// Manually curated entries below (hub currencies) were additionally verified
// against the live GGG feed + poe.ninja on 2026-08-18:
//   chaos->divine GGG 0.1056 vs ninja 0.1009  (5% match)
//   chaos->exalted GGG 33.5  vs ninja 33.45  (0.2% match)
//   mirror->divine GGG 4758  vs ninja 4759   (0.02% match)

import type { ItemId } from "./types";
import { GENERATED_MAPPING } from "./mapping.generated";

export const GGG_HUB_PATHS = {
  DIVINE: "Metadata/Items/Currency/CurrencyModValues",
  EXALTED: "Metadata/Items/Currency/CurrencyAddModToRare",
  CHAOS: "Metadata/Items/Currency/CurrencyRerollRare",
} as const;

const verified = "checked-in-verified" as const;

/** Manually curated entries (merged over generated ones for gold-cost fixes). */
const MANUAL_OVERRIDES: Record<string, ItemId> = {
  [GGG_HUB_PATHS.DIVINE]: {
    gggPath: GGG_HUB_PATHS.DIVINE,
    ninjaId: "divine",
    displayName: "Divine Orb",
    category: "Currency",
    iconUrl: null,
    goldCostPerUnit: 800,
    mappingSource: verified,
    lastVerifiedUtc: "2026-08-18T00:00:00Z",
  },
  [GGG_HUB_PATHS.EXALTED]: {
    gggPath: GGG_HUB_PATHS.EXALTED,
    ninjaId: "exalted",
    displayName: "Exalted Orb",
    category: "Currency",
    iconUrl: null,
    goldCostPerUnit: 120,
    mappingSource: verified,
    lastVerifiedUtc: "2026-08-18T00:00:00Z",
  },
  [GGG_HUB_PATHS.CHAOS]: {
    gggPath: GGG_HUB_PATHS.CHAOS,
    ninjaId: "chaos",
    displayName: "Chaos Orb",
    category: "Currency",
    iconUrl: null,
    goldCostPerUnit: 160,
    mappingSource: verified,
    lastVerifiedUtc: "2026-08-18T00:00:00Z",
  },
};

export const ITEM_MAP: Record<string, ItemId> = Object.fromEntries(
  Object.entries(GENERATED_MAPPING).map(([path, rec]) => [path, { ...rec.entry, mappingSource: verified }]),
);

// Apply manual overrides (gold costs from the poe2wiki exchange table).
for (const [path, item] of Object.entries(MANUAL_OVERRIDES)) {
  ITEM_MAP[path] = item;
}

export function lookupItem(gggPath: string): ItemId | null {
  return ITEM_MAP[gggPath] ?? null;
}

export function displayName(gggPath: string): string {
  return lookupItem(gggPath)?.displayName ?? gggPath.split("/").pop() ?? gggPath;
}

/**
 * Gold cost per received unit. If unmapped OR the fee is unverified (-1),
 * returns 0 and flags `verified: false` so the caller drops the route or marks
 * it low-confidence — never guess a fee, never treat an unknown fee as zero.
 */
export function goldCostPerUnit(gggPath: string): { cost: number; verified: boolean } {
  const item = lookupItem(gggPath);
  if (!item || item.mappingSource !== "checked-in-verified" || item.goldCostPerUnit < 0) {
    return { cost: 0, verified: false };
  }
  return { cost: item.goldCostPerUnit, verified: true };
}