// AUTO-GENERATED. Do not edit by hand — run `npx tsx scripts/generate-mapping.ts`.
// Provenance: cross-validated 2026-08-18 against GGG completed-hour feed
// (1787022000, league 'Runes of Aldur') and poe.ninja PoE2 economy overview.
// Verified entries matched within 25% of the poe.ninja implied rate across all
// observed markets. Quarantined entries failed the check and are NOT added.
import type { ItemId } from "./types";

export interface MappingRecord {
  entry: ItemId;
  /** implied divine rate from poe.ninja used for validation */
  validatedRate: number;
  /** number of independent market observations used */
  observations: number;
}

export const GENERATED_MAPPING: Record<string, MappingRecord> = {
  "Metadata/Items/Currency/CurrencyModValues": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyModValues",
      ninjaId: "divine",
      displayName: "Divine Orb",
      category: "Currency",
      iconUrl: "/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lNb2RWYWx1ZXMiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/2986e220b3/CurrencyModValues.png",
      goldCostPerUnit: 800,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 1,
    observations: 23,
  },
  "Metadata/Items/Currency/CurrencyAddModToRare": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyAddModToRare",
      ninjaId: "exalted",
      displayName: "Exalted Orb",
      category: "Currency",
      iconUrl: "/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lBZGRNb2RUb1JhcmUiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/ad7c366789/CurrencyAddModToRare.png",
      goldCostPerUnit: 120,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0.003016,
    observations: 22,
  },
  "Metadata/Items/Currency/CurrencyRerollRare": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyRerollRare",
      ninjaId: "chaos",
      displayName: "Chaos Orb",
      category: "Currency",
      iconUrl: "/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lSZXJvbGxSYXJlIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/c0ca392a78/CurrencyRerollRare.png",
      goldCostPerUnit: 160,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0.1009,
    observations: 21,
  },
  "Metadata/Items/Currency/CurrencyRerollRare2": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyRerollRare2",
      ninjaId: "greater-chaos-orb",
      displayName: "Greater Chaos Orb",
      category: "Currency",
      iconUrl: "/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lSZXJvbGxSYXJlIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/c0ca392a78/CurrencyRerollRare.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0.2961,
    observations: 6,
  },
  "Metadata/Items/Currency/CurrencyUpgradeToMagic": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyUpgradeToMagic",
      ninjaId: "transmute",
      displayName: "Orb of Transmutation",
      category: "Currency",
      iconUrl: "/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lVcGdyYWRlVG9NYWdpYyIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/2f8e1ff9f8/CurrencyUpgradeToMagic.png",
      goldCostPerUnit: 50,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0.0004293,
    observations: 4,
  },
  "Metadata/Items/Currency/CurrencyGemQuality": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyGemQuality",
      ninjaId: "gcp",
      displayName: "Gemcutter's Prism",
      category: "Currency",
      iconUrl: "/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lHZW1RdWFsaXR5Iiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/f4bace18d7/CurrencyGemQuality.png",
      goldCostPerUnit: 1000,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0.01799,
    observations: 4,
  },
  "Metadata/Items/Currency/CurrencyAddModToRare2": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyAddModToRare2",
      ninjaId: "greater-exalted-orb",
      displayName: "Greater Exalted Orb",
      category: "Currency",
      iconUrl: "/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lBZGRNb2RUb1JhcmUiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/ad7c366789/CurrencyAddModToRare.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0.01336,
    observations: 4,
  },
  "Metadata/Items/Currency/CurrencyAddModToRare3": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyAddModToRare3",
      ninjaId: "perfect-exalted-orb",
      displayName: "Perfect Exalted Orb",
      category: "Currency",
      iconUrl: "/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lBZGRNb2RUb1JhcmUiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/ad7c366789/CurrencyAddModToRare.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 2.23,
    observations: 4,
  },
  "Metadata/Items/Currency/CurrencyIdentification": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyIdentification",
      ninjaId: "wisdom",
      displayName: "Scroll of Wisdom",
      category: "Currency",
      iconUrl: "/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lJZGVudGlmaWNhdGlvbiIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/884f7bc58b/CurrencyIdentification.png",
      goldCostPerUnit: 1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0.00008,
    observations: 3,
  },
  "Metadata/Items/Currency/CurrencyAddModToMagic": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyAddModToMagic",
      ninjaId: "aug",
      displayName: "Orb of Augmentation",
      category: "Currency",
      iconUrl: "/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lBZGRNb2RUb01hZ2ljIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/c8ad0ddc84/CurrencyAddModToMagic.png",
      goldCostPerUnit: 200,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0.0004197,
    observations: 3,
  },
  "Metadata/Items/Currency/CurrencyUpgradeToRare": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyUpgradeToRare",
      ninjaId: "alch",
      displayName: "Orb of Alchemy",
      category: "Currency",
      iconUrl: "/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lVcGdyYWRlVG9SYXJlIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/9b80b44821/CurrencyUpgradeToRare.png",
      goldCostPerUnit: 200,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0.001989,
    observations: 3,
  },
  "Metadata/Items/Currency/CurrencyArmourQuality": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyArmourQuality",
      ninjaId: "scrap",
      displayName: "Armourer's Scrap",
      category: "Currency",
      iconUrl: "/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lBcm1vdXJRdWFsaXR5Iiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/d5868f596d/CurrencyArmourQuality.png",
      goldCostPerUnit: 250,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0.004055,
    observations: 3,
  },
  "Metadata/Items/Currency/CurrencyAddEquipmentSocket": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyAddEquipmentSocket",
      ninjaId: "artificers",
      displayName: "Artificer's Orb",
      category: "Currency",
      iconUrl: "/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lBZGRFcXVpcG1lbnRTb2NrZXQiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/5131fd4774/CurrencyAddEquipmentSocket.png",
      goldCostPerUnit: 1000,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0.001558,
    observations: 3,
  },
  "Metadata/Items/Currency/CurrencyRerollRare3": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyRerollRare3",
      ninjaId: "perfect-chaos-orb",
      displayName: "Perfect Chaos Orb",
      category: "Currency",
      iconUrl: "/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lSZXJvbGxSYXJlIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/c0ca392a78/CurrencyRerollRare.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 4.89,
    observations: 3,
  },
  "Metadata/Items/Currency/CurrencyAddModToMagic3": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyAddModToMagic3",
      ninjaId: "perfect-orb-of-augmentation",
      displayName: "Perfect Orb of Augmentation",
      category: "Currency",
      iconUrl: "/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lBZGRNb2RUb01hZ2ljIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/c8ad0ddc84/CurrencyAddModToMagic.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0.08836,
    observations: 3,
  },
  "Metadata/Items/Currency/CurrencyUpgradeToMagic3": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyUpgradeToMagic3",
      ninjaId: "perfect-orb-of-transmutation",
      displayName: "Perfect Orb of Transmutation",
      category: "Currency",
      iconUrl: "/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lVcGdyYWRlVG9NYWdpYyIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/2f8e1ff9f8/CurrencyUpgradeToMagic.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0.01319,
    observations: 3,
  },
  "Metadata/Items/Currency/CurrencyUpgradeMagicToRare2": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyUpgradeMagicToRare2",
      ninjaId: "greater-regal-orb",
      displayName: "Greater Regal Orb",
      category: "Currency",
      iconUrl: "/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lVcGdyYWRlTWFnaWNUb1JhcmUiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/e8fb148e80/CurrencyUpgradeMagicToRare.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0.01388,
    observations: 3,
  },
  "Metadata/Items/Currency/CurrencyUpgradeMagicToRare3": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyUpgradeMagicToRare3",
      ninjaId: "perfect-regal-orb",
      displayName: "Perfect Regal Orb",
      category: "Currency",
      iconUrl: "/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lVcGdyYWRlTWFnaWNUb1JhcmUiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/e8fb148e80/CurrencyUpgradeMagicToRare.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0.05455,
    observations: 3,
  },
  "Metadata/Items/Currency/CurrencyDuplicate": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyDuplicate",
      ninjaId: "mirror",
      displayName: "Mirror of Kalandra",
      category: "Currency",
      iconUrl: "/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lEdXBsaWNhdGUiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/26bc31680e/CurrencyDuplicate.png",
      goldCostPerUnit: 25000,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 4759,
    observations: 1,
  },
  "Metadata/Items/Currency/CurrencyHinekorasLock": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyHinekorasLock",
      ninjaId: "hinekoras-lock",
      displayName: "Hinekora's Lock",
      category: "Currency",
      iconUrl: "/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvSGluZWtvcmFzTG9jayIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/ab2163ae06/HinekorasLock.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 1139,
    observations: 1,
  },
};

// --- Authoritative identity-only entries (path+name+icon from poe.ninja) ---
export const AUTHORITATIVE_IDENTITY_MAPPING: Record<string, MappingRecord> = {
  "Metadata/Items/Currency/AnnullOrb": {
    entry: {
      gggPath: "Metadata/Items/Currency/AnnullOrb",
      ninjaId: "annul",
      displayName: "Orb of Annulment",
      category: "Currency",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQW5udWxsT3JiIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/2daba8ccca/AnnullOrb.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/Breach/BreachCatalystAttack": {
    entry: {
      gggPath: "Metadata/Items/Currency/Breach/BreachCatalystAttack",
      ninjaId: "reaver-catalyst",
      displayName: "Reaver Catalyst",
      category: "Breach",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQnJlYWNoL0JyZWFjaENhdGFseXN0QXR0YWNrIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/ccc363f502/BreachCatalystAttack.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/Breach/BreachCatalystAttribute": {
    entry: {
      gggPath: "Metadata/Items/Currency/Breach/BreachCatalystAttribute",
      ninjaId: "adaptive-catalyst",
      displayName: "Adaptive Catalyst",
      category: "Breach",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQnJlYWNoL0JyZWFjaENhdGFseXN0QXR0cmlidXRlIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/015f6c9ac8/BreachCatalystAttribute.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/Breach/BreachCatalystCaster": {
    entry: {
      gggPath: "Metadata/Items/Currency/Breach/BreachCatalystCaster",
      ninjaId: "sibilant-catalyst",
      displayName: "Sibilant Catalyst",
      category: "Breach",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQnJlYWNoL0JyZWFjaENhdGFseXN0Q2FzdGVyIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/51dc6bc317/BreachCatalystCaster.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/Breach/BreachCatalystChaos": {
    entry: {
      gggPath: "Metadata/Items/Currency/Breach/BreachCatalystChaos",
      ninjaId: "chayulas-catalyst",
      displayName: "Chayula's Catalyst",
      category: "Breach",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQnJlYWNoL0JyZWFjaENhdGFseXN0Q2hhb3MiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/c80d8d7b1b/BreachCatalystChaos.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/Breach/BreachCatalystCold": {
    entry: {
      gggPath: "Metadata/Items/Currency/Breach/BreachCatalystCold",
      ninjaId: "tuls-catalyst",
      displayName: "Tul's Catalyst",
      category: "Breach",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQnJlYWNoL0JyZWFjaENhdGFseXN0Q29sZCIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/c3bc9abf43/BreachCatalystCold.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/Breach/BreachCatalystDefences": {
    entry: {
      gggPath: "Metadata/Items/Currency/Breach/BreachCatalystDefences",
      ninjaId: "carapace-catalyst",
      displayName: "Carapace Catalyst",
      category: "Breach",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQnJlYWNoL0JyZWFjaENhdGFseXN0RGVmZW5jZXMiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/568ca70b04/BreachCatalystDefences.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/Breach/BreachCatalystFire": {
    entry: {
      gggPath: "Metadata/Items/Currency/Breach/BreachCatalystFire",
      ninjaId: "xophs-catalyst",
      displayName: "Xoph's Catalyst",
      category: "Breach",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQnJlYWNoL0JyZWFjaENhdGFseXN0RmlyZSIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/05b1999374/BreachCatalystFire.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/Breach/BreachCatalystLife": {
    entry: {
      gggPath: "Metadata/Items/Currency/Breach/BreachCatalystLife",
      ninjaId: "flesh-catalyst",
      displayName: "Flesh Catalyst",
      category: "Breach",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQnJlYWNoL0JyZWFjaENhdGFseXN0TGlmZSIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/06ec489870/BreachCatalystLife.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/Breach/BreachCatalystLightning": {
    entry: {
      gggPath: "Metadata/Items/Currency/Breach/BreachCatalystLightning",
      ninjaId: "eshs-catalyst",
      displayName: "Esh's Catalyst",
      category: "Breach",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQnJlYWNoL0JyZWFjaENhdGFseXN0TGlnaHRuaW5nIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/299e62fc33/BreachCatalystLightning.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/Breach/BreachCatalystMana": {
    entry: {
      gggPath: "Metadata/Items/Currency/Breach/BreachCatalystMana",
      ninjaId: "neural-catalyst",
      displayName: "Neural Catalyst",
      category: "Breach",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQnJlYWNoL0JyZWFjaENhdGFseXN0TWFuYSIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/61d3a7a832/BreachCatalystMana.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/Breach/BreachCatalystNecrotic": {
    entry: {
      gggPath: "Metadata/Items/Currency/Breach/BreachCatalystNecrotic",
      ninjaId: "necrotic-catalyst",
      displayName: "Necrotic Catalyst",
      category: "Breach",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQnJlYWNoL0JyZWFjaENhdGFseXN0TmVjcm90aWMiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/5e20b43820/BreachCatalystNecrotic.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/Breach/BreachCatalystPhysical": {
    entry: {
      gggPath: "Metadata/Items/Currency/Breach/BreachCatalystPhysical",
      ninjaId: "uul-netols-catalyst",
      displayName: "Uul-Netol's Catalyst",
      category: "Breach",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQnJlYWNoL0JyZWFjaENhdGFseXN0UGh5c2ljYWwiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/bc9406c106/BreachCatalystPhysical.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/Breach/BreachCatalystSpeed": {
    entry: {
      gggPath: "Metadata/Items/Currency/Breach/BreachCatalystSpeed",
      ninjaId: "skittering-catalyst",
      displayName: "Skittering Catalyst",
      category: "Breach",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQnJlYWNoL0JyZWFjaENhdGFseXN0U3BlZWQiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/14b5db3c3c/BreachCatalystSpeed.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/Breach/Breachstone": {
    entry: {
      gggPath: "Metadata/Items/Currency/Breach/Breachstone",
      ninjaId: "breachstone",
      displayName: "Breachstone",
      category: "Breach",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQnJlYWNoL0JyZWFjaHN0b25lIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/d60587d724/Breachstone.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/Breach/BreachstoneSplinter": {
    entry: {
      gggPath: "Metadata/Items/Currency/Breach/BreachstoneSplinter",
      ninjaId: "breach-splinter",
      displayName: "Breach Splinter",
      category: "Breach",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQnJlYWNoL0JyZWFjaHN0b25lU3BsaW50ZXIiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/4abb17ea8e/BreachstoneSplinter.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/Breach/JewelCatalystAttack": {
    entry: {
      gggPath: "Metadata/Items/Currency/Breach/JewelCatalystAttack",
      ninjaId: "refined-reaver-catalyst",
      displayName: "Refined Reaver Catalyst",
      category: "Breach",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQnJlYWNoL0pld2VsQ2F0YWx5c3RBdHRhY2siLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/9c13494ea8/JewelCatalystAttack.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/Breach/JewelCatalystAttribute": {
    entry: {
      gggPath: "Metadata/Items/Currency/Breach/JewelCatalystAttribute",
      ninjaId: "refined-adaptive-catalyst",
      displayName: "Refined Adaptive Catalyst",
      category: "Breach",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQnJlYWNoL0pld2VsQ2F0YWx5c3RBdHRyaWJ1dGUiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/6fba81f1c7/JewelCatalystAttribute.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/Breach/JewelCatalystCaster": {
    entry: {
      gggPath: "Metadata/Items/Currency/Breach/JewelCatalystCaster",
      ninjaId: "refined-sibilant-catalyst",
      displayName: "Refined Sibilant Catalyst",
      category: "Breach",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQnJlYWNoL0pld2VsQ2F0YWx5c3RDYXN0ZXIiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/280306d9e0/JewelCatalystCaster.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/Breach/JewelCatalystChaos": {
    entry: {
      gggPath: "Metadata/Items/Currency/Breach/JewelCatalystChaos",
      ninjaId: "refined-chayulas-catalyst",
      displayName: "Refined Chayula's Catalyst",
      category: "Breach",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQnJlYWNoL0pld2VsQ2F0YWx5c3RDaGFvcyIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/162124aa67/JewelCatalystChaos.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/Breach/JewelCatalystCold": {
    entry: {
      gggPath: "Metadata/Items/Currency/Breach/JewelCatalystCold",
      ninjaId: "refined-tuls-catalyst",
      displayName: "Refined Tul's Catalyst",
      category: "Breach",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQnJlYWNoL0pld2VsQ2F0YWx5c3RDb2xkIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/1b256097c6/JewelCatalystCold.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/Breach/JewelCatalystDefences": {
    entry: {
      gggPath: "Metadata/Items/Currency/Breach/JewelCatalystDefences",
      ninjaId: "refined-carapace-catalyst",
      displayName: "Refined Carapace Catalyst",
      category: "Breach",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQnJlYWNoL0pld2VsQ2F0YWx5c3REZWZlbmNlcyIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/a4d02de8e3/JewelCatalystDefences.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/Breach/JewelCatalystFire": {
    entry: {
      gggPath: "Metadata/Items/Currency/Breach/JewelCatalystFire",
      ninjaId: "refined-xophs-catalyst",
      displayName: "Refined Xoph's Catalyst",
      category: "Breach",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQnJlYWNoL0pld2VsQ2F0YWx5c3RGaXJlIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/d584c5922b/JewelCatalystFire.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/Breach/JewelCatalystLife": {
    entry: {
      gggPath: "Metadata/Items/Currency/Breach/JewelCatalystLife",
      ninjaId: "refined-flesh-catalyst",
      displayName: "Refined Flesh Catalyst",
      category: "Breach",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQnJlYWNoL0pld2VsQ2F0YWx5c3RMaWZlIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/b210729498/JewelCatalystLife.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/Breach/JewelCatalystLightning": {
    entry: {
      gggPath: "Metadata/Items/Currency/Breach/JewelCatalystLightning",
      ninjaId: "refined-eshs-catalyst",
      displayName: "Refined Esh's Catalyst",
      category: "Breach",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQnJlYWNoL0pld2VsQ2F0YWx5c3RMaWdodG5pbmciLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/55ca761293/JewelCatalystLightning.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/Breach/JewelCatalystMana": {
    entry: {
      gggPath: "Metadata/Items/Currency/Breach/JewelCatalystMana",
      ninjaId: "refined-neural-catalyst",
      displayName: "Refined Neural Catalyst",
      category: "Breach",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQnJlYWNoL0pld2VsQ2F0YWx5c3RNYW5hIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/141d460ed9/JewelCatalystMana.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/Breach/JewelCatalystNecrotic": {
    entry: {
      gggPath: "Metadata/Items/Currency/Breach/JewelCatalystNecrotic",
      ninjaId: "refined-necrotic-catalyst",
      displayName: "Refined Necrotic Catalyst",
      category: "Breach",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQnJlYWNoL0pld2VsQ2F0YWx5c3ROZWNyb3RpYyIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/4e691d8472/JewelCatalystNecrotic.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/Breach/JewelCatalystPhysical": {
    entry: {
      gggPath: "Metadata/Items/Currency/Breach/JewelCatalystPhysical",
      ninjaId: "refined-uul-netols-catalyst",
      displayName: "Refined Uul-Netol's Catalyst",
      category: "Breach",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQnJlYWNoL0pld2VsQ2F0YWx5c3RQaHlzaWNhbCIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/af62c7f7d8/JewelCatalystPhysical.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/Breach/JewelCatalystSpeed": {
    entry: {
      gggPath: "Metadata/Items/Currency/Breach/JewelCatalystSpeed",
      ninjaId: "refined-skittering-catalyst",
      displayName: "Refined Skittering Catalyst",
      category: "Breach",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQnJlYWNoL0pld2VsQ2F0YWx5c3RTcGVlZCIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/680cbc13b1/JewelCatalystSpeed.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/CurrencyAddEquipmentSocketShard": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyAddEquipmentSocketShard",
      ninjaId: "artificers-shard",
      displayName: "Artificer's Shard",
      category: "Currency",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lBZGRFcXVpcG1lbnRTb2NrZXRTaGFyZCIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/cdcdd8bf3f/CurrencyAddEquipmentSocketShard.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/CurrencyFlaskQuality": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyFlaskQuality",
      ninjaId: "bauble",
      displayName: "Glassblower's Bauble",
      category: "Currency",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lGbGFza1F1YWxpdHkiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/1cec279e01/CurrencyFlaskQuality.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/CurrencyRerollSocketNumbers01": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyRerollSocketNumbers01",
      ninjaId: "lesser-jewellers-orb",
      displayName: "Lesser Jeweller's Orb",
      category: "Currency",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lSZXJvbGxTb2NrZXROdW1iZXJzMDEiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/b0b9a43ed8/CurrencyRerollSocketNumbers01.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/CurrencyRerollSocketNumbers02": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyRerollSocketNumbers02",
      ninjaId: "greater-jewellers-orb",
      displayName: "Greater Jeweller's Orb",
      category: "Currency",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lSZXJvbGxTb2NrZXROdW1iZXJzMDIiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/7dd6ee75be/CurrencyRerollSocketNumbers02.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/CurrencyRerollSocketNumbers03": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyRerollSocketNumbers03",
      ninjaId: "perfect-jewellers-orb",
      displayName: "Perfect Jeweller's Orb",
      category: "Currency",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lSZXJvbGxTb2NrZXROdW1iZXJzMDMiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/ac6398e6a0/CurrencyRerollSocketNumbers03.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/CurrencyUpgradeToUnique": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyUpgradeToUnique",
      ninjaId: "chance",
      displayName: "Orb of Chance",
      category: "Currency",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lVcGdyYWRlVG9VbmlxdWUiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/93c6cc8d5b/CurrencyUpgradeToUnique.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/CurrencyUpgradeToUniqueShard": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyUpgradeToUniqueShard",
      ninjaId: "chance-shard",
      displayName: "Chance Shard",
      category: "Currency",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lVcGdyYWRlVG9VbmlxdWVTaGFyZCIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/9828a70270/CurrencyUpgradeToUniqueShard.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/CurrencyVaal": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyVaal",
      ninjaId: "vaal",
      displayName: "Vaal Orb",
      category: "Currency",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lWYWFsIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/72bc84396c/CurrencyVaal.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/CurrencyWeaponMagicQuality": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyWeaponMagicQuality",
      ninjaId: "etcher",
      displayName: "Arcanist's Etcher",
      category: "Currency",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lXZWFwb25NYWdpY1F1YWxpdHkiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/516e8f1131/CurrencyWeaponMagicQuality.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/CurrencyWeaponQuality": {
    entry: {
      gggPath: "Metadata/Items/Currency/CurrencyWeaponQuality",
      ninjaId: "whetstone",
      displayName: "Blacksmith's Whetstone",
      category: "Currency",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lXZWFwb25RdWFsaXR5Iiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/18715ea7be/CurrencyWeaponQuality.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/Delirium/DeliriumEndgameSocketable": {
    entry: {
      gggPath: "Metadata/Items/Currency/Delirium/DeliriumEndgameSocketable",
      ninjaId: "raven-touched-shard",
      displayName: "Raven-Touched Shard",
      category: "Ritual",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRGVsaXJpdW0vRGVsaXJpdW1FbmRnYW1lU29ja2V0YWJsZSIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/8ad4972b7b/DeliriumEndgameSocketable.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/Expedition2/ArcaneFlux": {
    entry: {
      gggPath: "Metadata/Items/Currency/Expedition2/ArcaneFlux",
      ninjaId: "void-flux",
      displayName: "Void Flux",
      category: "Expedition",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXhwZWRpdGlvbjIvQXJjYW5lRmx1eCIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/05c5ace7f7/ArcaneFlux.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/Expedition2/ArcaneFluxCold": {
    entry: {
      gggPath: "Metadata/Items/Currency/Expedition2/ArcaneFluxCold",
      ninjaId: "chilling-flux",
      displayName: "Chilling Flux",
      category: "Expedition",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXhwZWRpdGlvbjIvQXJjYW5lRmx1eENvbGQiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/8be4ea67ff/ArcaneFluxCold.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/Expedition2/ArcaneFluxFire": {
    entry: {
      gggPath: "Metadata/Items/Currency/Expedition2/ArcaneFluxFire",
      ninjaId: "blazing-flux",
      displayName: "Blazing Flux",
      category: "Expedition",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXhwZWRpdGlvbjIvQXJjYW5lRmx1eEZpcmUiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/5894d96668/ArcaneFluxFire.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/Expedition2/ArcaneFluxLightning": {
    entry: {
      gggPath: "Metadata/Items/Currency/Expedition2/ArcaneFluxLightning",
      ninjaId: "crackling-flux",
      displayName: "Crackling Flux",
      category: "Expedition",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXhwZWRpdGlvbjIvQXJjYW5lRmx1eExpZ2h0bmluZyIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/6f9758e0a3/ArcaneFluxLightning.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/Expedition2/ExpeditionGemCurrencyPowerful": {
    entry: {
      gggPath: "Metadata/Items/Currency/Expedition2/ExpeditionGemCurrencyPowerful",
      ninjaId: "perfect-flux",
      displayName: "Perfect Flux",
      category: "Expedition",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXhwZWRpdGlvbjIvRXhwZWRpdGlvbkdlbUN1cnJlbmN5UG93ZXJmdWwiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/43be23e971/ExpeditionGemCurrencyPowerful.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/Expedition2/ExpeditionLogbook5": {
    entry: {
      gggPath: "Metadata/Items/Currency/Expedition2/ExpeditionLogbook5",
      ninjaId: "expedition-logbook",
      displayName: "Expedition Logbook",
      category: "Expedition",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXhwZWRpdGlvbjIvRXhwZWRpdGlvbkxvZ2Jvb2s1Iiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/841a5e9622/ExpeditionLogbook5.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/Expedition2/SpecialExpeditionPage1": {
    entry: {
      gggPath: "Metadata/Items/Currency/Expedition2/SpecialExpeditionPage1",
      ninjaId: "olroths-saga",
      displayName: "Olroth's Saga",
      category: "Expedition",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXhwZWRpdGlvbjIvU3BlY2lhbEV4cGVkaXRpb25QYWdlMSIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/e4b423d772/SpecialExpeditionPage1.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/Expedition2/SpecialExpeditionPage2": {
    entry: {
      gggPath: "Metadata/Items/Currency/Expedition2/SpecialExpeditionPage2",
      ninjaId: "voranas-saga",
      displayName: "Vorana's Saga",
      category: "Expedition",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXhwZWRpdGlvbjIvU3BlY2lhbEV4cGVkaXRpb25QYWdlMiIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/057899d625/SpecialExpeditionPage2.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/Expedition2/SpecialExpeditionPage3": {
    entry: {
      gggPath: "Metadata/Items/Currency/Expedition2/SpecialExpeditionPage3",
      ninjaId: "medveds-saga",
      displayName: "Medved's Saga",
      category: "Expedition",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXhwZWRpdGlvbjIvU3BlY2lhbEV4cGVkaXRpb25QYWdlMyIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/9eb5b576fc/SpecialExpeditionPage3.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/Expedition2/SpecialExpeditionPage4": {
    entry: {
      gggPath: "Metadata/Items/Currency/Expedition2/SpecialExpeditionPage4",
      ninjaId: "uhtreds-saga",
      displayName: "Uhtred's Saga",
      category: "Expedition",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXhwZWRpdGlvbjIvU3BlY2lhbEV4cGVkaXRpb25QYWdlNCIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/0470c24911/SpecialExpeditionPage4.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/Expedition2/SpecialExpeditionPage5": {
    entry: {
      gggPath: "Metadata/Items/Currency/Expedition2/SpecialExpeditionPage5",
      ninjaId: "aldurs-saga",
      displayName: "Aldur's Saga",
      category: "Expedition",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXhwZWRpdGlvbjIvU3BlY2lhbEV4cGVkaXRpb25QYWdlNSIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/e4e66b1f57/SpecialExpeditionPage5.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/FracturingOrb": {
    entry: {
      gggPath: "Metadata/Items/Currency/FracturingOrb",
      ninjaId: "fracturing-orb",
      displayName: "Fracturing Orb",
      category: "Currency",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRnJhY3R1cmluZ09yYiIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/8b85ed1dc2/FracturingOrb.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/HinekorasLock": {
    entry: {
      gggPath: "Metadata/Items/Currency/HinekorasLock",
      ninjaId: "hinekoras-lock",
      displayName: "Hinekora's Lock",
      category: "Currency",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvSGluZWtvcmFzTG9jayIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/ab2163ae06/HinekorasLock.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/IncursionCraftingOrbs/IncursionAncientInfusion": {
    entry: {
      gggPath: "Metadata/Items/Currency/IncursionCraftingOrbs/IncursionAncientInfusion",
      ninjaId: "ancient-infuser",
      displayName: "Ancient Infuser",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvSW5jdXJzaW9uQ3JhZnRpbmdPcmJzL0luY3Vyc2lvbkFuY2llbnRJbmZ1c2lvbiIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/7d23730590/IncursionAncientInfusion.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/IncursionCraftingOrbs/IncursionCoreDestabliser": {
    entry: {
      gggPath: "Metadata/Items/Currency/IncursionCraftingOrbs/IncursionCoreDestabliser",
      ninjaId: "core-destabiliser",
      displayName: "Core Destabiliser",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvSW5jdXJzaW9uQ3JhZnRpbmdPcmJzL0luY3Vyc2lvbkNvcmVEZXN0YWJsaXNlciIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/e613c14ed7/IncursionCoreDestabliser.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/IncursionCraftingOrbs/IncursionCorruptionOrb1": {
    entry: {
      gggPath: "Metadata/Items/Currency/IncursionCraftingOrbs/IncursionCorruptionOrb1",
      ninjaId: "yaomacs-orb-of-sacrifice",
      displayName: "Yaomac's Orb of Sacrifice",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvSW5jdXJzaW9uQ3JhZnRpbmdPcmJzL0luY3Vyc2lvbkNvcnJ1cHRpb25PcmIxIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/d8bf3af5d5/IncursionCorruptionOrb1.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/IncursionCraftingOrbs/IncursionCorruptionOrb2": {
    entry: {
      gggPath: "Metadata/Items/Currency/IncursionCraftingOrbs/IncursionCorruptionOrb2",
      ninjaId: "kopecs-orb-of-sacrifice",
      displayName: "Kopec's Orb of Sacrifice",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvSW5jdXJzaW9uQ3JhZnRpbmdPcmJzL0luY3Vyc2lvbkNvcnJ1cHRpb25PcmIyIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/911b28ea18/IncursionCorruptionOrb2.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/IncursionCraftingOrbs/IncursionCorruptionOrb3": {
    entry: {
      gggPath: "Metadata/Items/Currency/IncursionCraftingOrbs/IncursionCorruptionOrb3",
      ninjaId: "kamasas-orb-of-sacrifice",
      displayName: "Kamasa's Orb of Sacrifice",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvSW5jdXJzaW9uQ3JhZnRpbmdPcmJzL0luY3Vyc2lvbkNvcnJ1cHRpb25PcmIzIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/00e0cd1060/IncursionCorruptionOrb3.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/IncursionCraftingOrbs/IncursionCorruptionOrb4": {
    entry: {
      gggPath: "Metadata/Items/Currency/IncursionCraftingOrbs/IncursionCorruptionOrb4",
      ninjaId: "yuguls-orb-of-sacrifice",
      displayName: "Yugul's Orb of Sacrifice",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvSW5jdXJzaW9uQ3JhZnRpbmdPcmJzL0luY3Vyc2lvbkNvcnJ1cHRpb25PcmI0Iiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/5102a7c2f5/IncursionCorruptionOrb4.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/IncursionCraftingOrbs/IncursionCrystallisedCorruption": {
    entry: {
      gggPath: "Metadata/Items/Currency/IncursionCraftingOrbs/IncursionCrystallisedCorruption",
      ninjaId: "crystallised-corruption",
      displayName: "Crystallised Corruption",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvSW5jdXJzaW9uQ3JhZnRpbmdPcmJzL0luY3Vyc2lvbkNyeXN0YWxsaXNlZENvcnJ1cHRpb24iLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/7bb759396f/IncursionCrystallisedCorruption.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/IncursionCraftingOrbs/IncursionGreaterVaalOrb": {
    entry: {
      gggPath: "Metadata/Items/Currency/IncursionCraftingOrbs/IncursionGreaterVaalOrb",
      ninjaId: "architects-orb",
      displayName: "Architect's Orb",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvSW5jdXJzaW9uQ3JhZnRpbmdPcmJzL0luY3Vyc2lvbkdyZWF0ZXJWYWFsT3JiIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/7ba6f79f63/IncursionGreaterVaalOrb.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/IncursionCraftingOrbs/IncursionHistoricVaalOrb": {
    entry: {
      gggPath: "Metadata/Items/Currency/IncursionCraftingOrbs/IncursionHistoricVaalOrb",
      ninjaId: "vaal-cultivation-orb",
      displayName: "Vaal Cultivation Orb",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvSW5jdXJzaW9uQ3JhZnRpbmdPcmJzL0luY3Vyc2lvbkhpc3RvcmljVmFhbE9yYiIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/07d4d75931/IncursionHistoricVaalOrb.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/IncursionCraftingOrbs/IncursionSocketableExtractorCurrency": {
    entry: {
      gggPath: "Metadata/Items/Currency/IncursionCraftingOrbs/IncursionSocketableExtractorCurrency",
      ninjaId: "orb-of-extraction",
      displayName: "Orb of Extraction",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvSW5jdXJzaW9uQ3JhZnRpbmdPcmJzL0luY3Vyc2lvblNvY2tldGFibGVFeHRyYWN0b3JDdXJyZW5jeSIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/dae9dfbb5e/IncursionSocketableExtractorCurrency.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/IncursionCraftingOrbs/IncursionVaalSiphoner": {
    entry: {
      gggPath: "Metadata/Items/Currency/IncursionCraftingOrbs/IncursionVaalSiphoner",
      ninjaId: "vaal-siphoner",
      displayName: "Vaal Siphoner",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvSW5jdXJzaW9uQ3JhZnRpbmdPcmJzL0luY3Vyc2lvblZhYWxTaXBob25lciIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/070fd020d7/IncursionVaalSiphoner.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/IncursionCraftingOrbs/VaakArmourersScrap": {
    entry: {
      gggPath: "Metadata/Items/Currency/IncursionCraftingOrbs/VaakArmourersScrap",
      ninjaId: "vaal-armourers-infuser",
      displayName: "Vaal Armourer's Infuser",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvSW5jdXJzaW9uQ3JhZnRpbmdPcmJzL1ZhYWtBcm1vdXJlcnNTY3JhcCIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/f9e1c7e389/VaakArmourersScrap.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/IncursionCraftingOrbs/VaalArcanistsEtcher": {
    entry: {
      gggPath: "Metadata/Items/Currency/IncursionCraftingOrbs/VaalArcanistsEtcher",
      ninjaId: "vaal-arcanists-infuser",
      displayName: "Vaal Arcanist's Infuser",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvSW5jdXJzaW9uQ3JhZnRpbmdPcmJzL1ZhYWxBcmNhbmlzdHNFdGNoZXIiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/3eb344ecc5/VaalArcanistsEtcher.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/IncursionCraftingOrbs/VaalBlacksmithsWhetstone": {
    entry: {
      gggPath: "Metadata/Items/Currency/IncursionCraftingOrbs/VaalBlacksmithsWhetstone",
      ninjaId: "vaal-blacksmiths-infuser",
      displayName: "Vaal Blacksmith's Infuser",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvSW5jdXJzaW9uQ3JhZnRpbmdPcmJzL1ZhYWxCbGFja3NtaXRoc1doZXRzdG9uZSIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/193a2f8085/VaalBlacksmithsWhetstone.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/IncursionCraftingOrbs/VaalCatalyst": {
    entry: {
      gggPath: "Metadata/Items/Currency/IncursionCraftingOrbs/VaalCatalyst",
      ninjaId: "vaal-catalysing-infuser",
      displayName: "Vaal Catalysing Infuser",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvSW5jdXJzaW9uQ3JhZnRpbmdPcmJzL1ZhYWxDYXRhbHlzdCIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/1c9f7be28c/VaalCatalyst.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/PerfectSoulCores/SoulCoreBlood": {
    entry: {
      gggPath: "Metadata/Items/Currency/PerfectSoulCores/SoulCoreBlood",
      ninjaId: "guatelitzis-thesis",
      displayName: "Guatelitzi's Thesis",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvUGVyZmVjdFNvdWxDb3Jlcy9Tb3VsQ29yZUJsb29kIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/eaea6fa77d/SoulCoreBlood.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/PerfectSoulCores/SoulCoreSacrifice": {
    entry: {
      gggPath: "Metadata/Items/Currency/PerfectSoulCores/SoulCoreSacrifice",
      ninjaId: "citaqualotls-thesis",
      displayName: "Citaqualotl's Thesis",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvUGVyZmVjdFNvdWxDb3Jlcy9Tb3VsQ29yZVNhY3JpZmljZSIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/3992461883/SoulCoreSacrifice.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/PerfectSoulCores/SoulCoreScience": {
    entry: {
      gggPath: "Metadata/Items/Currency/PerfectSoulCores/SoulCoreScience",
      ninjaId: "quipolatls-thesis",
      displayName: "Quipolatl's Thesis",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvUGVyZmVjdFNvdWxDb3Jlcy9Tb3VsQ29yZVNjaWVuY2UiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/2ab351d258/SoulCoreScience.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/PerfectSoulCores/SoulCoreSoul": {
    entry: {
      gggPath: "Metadata/Items/Currency/PerfectSoulCores/SoulCoreSoul",
      ninjaId: "jiquanis-thesis",
      displayName: "Jiquani's Thesis",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvUGVyZmVjdFNvdWxDb3Jlcy9Tb3VsQ29yZVNvdWwiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/a45ab2bca2/SoulCoreSoul.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/SoulCores/GreaterSoulCoreChaos": {
    entry: {
      gggPath: "Metadata/Items/Currency/SoulCores/GreaterSoulCoreChaos",
      ninjaId: "soul-core-of-tacati",
      displayName: "Soul Core of Tacati",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU291bENvcmVzL0dyZWF0ZXJTb3VsQ29yZUNoYW9zIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/cd9c4fb0a7/GreaterSoulCoreChaos.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/SoulCores/GreaterSoulCoreCold": {
    entry: {
      gggPath: "Metadata/Items/Currency/SoulCores/GreaterSoulCoreCold",
      ninjaId: "soul-core-of-tzamoto",
      displayName: "Soul Core of Tzamoto",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU291bENvcmVzL0dyZWF0ZXJTb3VsQ29yZUNvbGQiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/d437c04d5e/GreaterSoulCoreCold.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/SoulCores/GreaterSoulCoreCrit": {
    entry: {
      gggPath: "Metadata/Items/Currency/SoulCores/GreaterSoulCoreCrit",
      ninjaId: "soul-core-of-ticaba",
      displayName: "Soul Core of Ticaba",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU291bENvcmVzL0dyZWF0ZXJTb3VsQ29yZUNyaXQiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/b453416064/GreaterSoulCoreCrit.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/SoulCores/GreaterSoulCoreDex": {
    entry: {
      gggPath: "Metadata/Items/Currency/SoulCores/GreaterSoulCoreDex",
      ninjaId: "soul-core-of-cholotl",
      displayName: "Soul Core of Cholotl",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU291bENvcmVzL0dyZWF0ZXJTb3VsQ29yZURleCIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/c732c8a579/GreaterSoulCoreDex.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/SoulCores/GreaterSoulCoreElementalResist": {
    entry: {
      gggPath: "Metadata/Items/Currency/SoulCores/GreaterSoulCoreElementalResist",
      ninjaId: "soul-core-of-citaqualotl",
      displayName: "Soul Core of Citaqualotl",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU291bENvcmVzL0dyZWF0ZXJTb3VsQ29yZUVsZW1lbnRhbFJlc2lzdCIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/b8926e8826/GreaterSoulCoreElementalResist.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/SoulCores/GreaterSoulCoreFire": {
    entry: {
      gggPath: "Metadata/Items/Currency/SoulCores/GreaterSoulCoreFire",
      ninjaId: "soul-core-of-puhuarte",
      displayName: "Soul Core of Puhuarte",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU291bENvcmVzL0dyZWF0ZXJTb3VsQ29yZUZpcmUiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/6390ebeaa6/GreaterSoulCoreFire.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/SoulCores/GreaterSoulCoreint": {
    entry: {
      gggPath: "Metadata/Items/Currency/SoulCores/GreaterSoulCoreint",
      ninjaId: "soul-core-of-zantipi",
      displayName: "Soul Core of Zantipi",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU291bENvcmVzL0dyZWF0ZXJTb3VsQ29yZWludCIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/bf932f7001/GreaterSoulCoreint.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/SoulCores/GreaterSoulCoreLife": {
    entry: {
      gggPath: "Metadata/Items/Currency/SoulCores/GreaterSoulCoreLife",
      ninjaId: "soul-core-of-jiquani",
      displayName: "Soul Core of Jiquani",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU291bENvcmVzL0dyZWF0ZXJTb3VsQ29yZUxpZmUiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/bb83a9f337/GreaterSoulCoreLife.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/SoulCores/GreaterSoulCoreLightning": {
    entry: {
      gggPath: "Metadata/Items/Currency/SoulCores/GreaterSoulCoreLightning",
      ninjaId: "soul-core-of-xopec",
      displayName: "Soul Core of Xopec",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU291bENvcmVzL0dyZWF0ZXJTb3VsQ29yZUxpZ2h0bmluZyIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/3dffadfa9a/GreaterSoulCoreLightning.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/SoulCores/GreaterSoulCoreMana": {
    entry: {
      gggPath: "Metadata/Items/Currency/SoulCores/GreaterSoulCoreMana",
      ninjaId: "soul-core-of-zalatl",
      displayName: "Soul Core of Zalatl",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU291bENvcmVzL0dyZWF0ZXJTb3VsQ29yZU1hbmEiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/1437190de2/GreaterSoulCoreMana.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/SoulCores/GreaterSoulCorePhysical": {
    entry: {
      gggPath: "Metadata/Items/Currency/SoulCores/GreaterSoulCorePhysical",
      ninjaId: "soul-core-of-opiloti",
      displayName: "Soul Core of Opiloti",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU291bENvcmVzL0dyZWF0ZXJTb3VsQ29yZVBoeXNpY2FsIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/366f87b8f2/GreaterSoulCorePhysical.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/SoulCores/GreaterSoulCoreSpeed": {
    entry: {
      gggPath: "Metadata/Items/Currency/SoulCores/GreaterSoulCoreSpeed",
      ninjaId: "soul-core-of-quipolatl",
      displayName: "Soul Core of Quipolatl",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU291bENvcmVzL0dyZWF0ZXJTb3VsQ29yZVNwZWVkIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/d4967ad0f1/GreaterSoulCoreSpeed.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/SoulCores/GreaterSoulCoreStrength": {
    entry: {
      gggPath: "Metadata/Items/Currency/SoulCores/GreaterSoulCoreStrength",
      ninjaId: "soul-core-of-atmohua",
      displayName: "Soul Core of Atmohua",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU291bENvcmVzL0dyZWF0ZXJTb3VsQ29yZVN0cmVuZ3RoIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/1b37135049/GreaterSoulCoreStrength.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/SoulCores/GreaterSoulCoreTriElement": {
    entry: {
      gggPath: "Metadata/Items/Currency/SoulCores/GreaterSoulCoreTriElement",
      ninjaId: "soul-core-of-topotante",
      displayName: "Soul Core of Topotante",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU291bENvcmVzL0dyZWF0ZXJTb3VsQ29yZVRyaUVsZW1lbnQiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/ae7a949b3a/GreaterSoulCoreTriElement.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/SoulCores/GreaterSoulCoreWealthRarity": {
    entry: {
      gggPath: "Metadata/Items/Currency/SoulCores/GreaterSoulCoreWealthRarity",
      ninjaId: "soul-core-of-azcapa",
      displayName: "Soul Core of Azcapa",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU291bENvcmVzL0dyZWF0ZXJTb3VsQ29yZVdlYWx0aFJhcml0eSIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/6a69033a04/GreaterSoulCoreWealthRarity.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/SoulCores/NewSoulCoreChaos1": {
    entry: {
      gggPath: "Metadata/Items/Currency/SoulCores/NewSoulCoreChaos1",
      ninjaId: "tacatis-soul-core-of-affliction",
      displayName: "Tacati's Soul Core of Affliction",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU291bENvcmVzL05ld1NvdWxDb3JlQ2hhb3MxIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/276b585906/NewSoulCoreChaos1.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/SoulCores/NewSoulCoreChaos2": {
    entry: {
      gggPath: "Metadata/Items/Currency/SoulCores/NewSoulCoreChaos2",
      ninjaId: "citaqualotls-soul-core-of-foulness",
      displayName: "Citaqualotl's Soul Core of Foulness",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU291bENvcmVzL05ld1NvdWxDb3JlQ2hhb3MyIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/002059f8f5/NewSoulCoreChaos2.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/SoulCores/NewSoulCoreCurses2": {
    entry: {
      gggPath: "Metadata/Items/Currency/SoulCores/NewSoulCoreCurses2",
      ninjaId: "uromotis-soul-core-of-attenuation",
      displayName: "Uromoti's Soul Core of Attenuation",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU291bENvcmVzL05ld1NvdWxDb3JlQ3Vyc2VzMiIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/25919ac93d/NewSoulCoreCurses2.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/SoulCores/NewSoulCoreEnduranceCharge": {
    entry: {
      gggPath: "Metadata/Items/Currency/SoulCores/NewSoulCoreEnduranceCharge",
      ninjaId: "guatelitzis-soul-core-of-endurance",
      displayName: "Guatelitzi's Soul Core of Endurance",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU291bENvcmVzL05ld1NvdWxDb3JlRW5kdXJhbmNlQ2hhcmdlIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/8da8c1e799/NewSoulCoreEnduranceCharge.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/SoulCores/NewSoulCoreEnergyShield": {
    entry: {
      gggPath: "Metadata/Items/Currency/SoulCores/NewSoulCoreEnergyShield",
      ninjaId: "atmohuas-soul-core-of-retreat",
      displayName: "Atmohua's Soul Core of Retreat",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU291bENvcmVzL05ld1NvdWxDb3JlRW5lcmd5U2hpZWxkIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/10e16bc3ea/NewSoulCoreEnergyShield.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/SoulCores/NewSoulCoreFire": {
    entry: {
      gggPath: "Metadata/Items/Currency/SoulCores/NewSoulCoreFire",
      ninjaId: "topotantes-soul-core-of-dampening",
      displayName: "Topotante's Soul Core of Dampening",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU291bENvcmVzL05ld1NvdWxDb3JlRmlyZSIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/3657368a8c/NewSoulCoreFire.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/SoulCores/NewSoulCoreFrenzyCharge": {
    entry: {
      gggPath: "Metadata/Items/Currency/SoulCores/NewSoulCoreFrenzyCharge",
      ninjaId: "opilotis-soul-core-of-assault",
      displayName: "Opiloti's Soul Core of Assault",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU291bENvcmVzL05ld1NvdWxDb3JlRnJlbnp5Q2hhcmdlIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/ce5c1bdfdc/NewSoulCoreFrenzyCharge.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/SoulCores/NewSoulCoreIce": {
    entry: {
      gggPath: "Metadata/Items/Currency/SoulCores/NewSoulCoreIce",
      ninjaId: "hayoxis-soul-core-of-heatproofing",
      displayName: "Hayoxi's Soul Core of Heatproofing",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU291bENvcmVzL05ld1NvdWxDb3JlSWNlIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/6d8455bff0/NewSoulCoreIce.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/SoulCores/NewSoulCoreLightning": {
    entry: {
      gggPath: "Metadata/Items/Currency/SoulCores/NewSoulCoreLightning",
      ninjaId: "zalatls-soul-core-of-insulation",
      displayName: "Zalatl's Soul Core of Insulation",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU291bENvcmVzL05ld1NvdWxDb3JlTGlnaHRuaW5nIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/80c455f775/NewSoulCoreLightning.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/SoulCores/NewSoulCoreMinion": {
    entry: {
      gggPath: "Metadata/Items/Currency/SoulCores/NewSoulCoreMinion",
      ninjaId: "xipocados-soul-core-of-dominion",
      displayName: "Xipocado's Soul Core of Dominion",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU291bENvcmVzL05ld1NvdWxDb3JlTWluaW9uIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/b1e7975db2/NewSoulCoreMinion.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/SoulCores/NewSoulCorePowerCharge": {
    entry: {
      gggPath: "Metadata/Items/Currency/SoulCores/NewSoulCorePowerCharge",
      ninjaId: "xopecs-soul-core-of-power",
      displayName: "Xopec's Soul Core of Power",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU291bENvcmVzL05ld1NvdWxDb3JlUG93ZXJDaGFyZ2UiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/083d39a63b/NewSoulCorePowerCharge.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/SoulCores/NewSoulCoreProjectile": {
    entry: {
      gggPath: "Metadata/Items/Currency/SoulCores/NewSoulCoreProjectile",
      ninjaId: "cholotls-soul-core-of-war",
      displayName: "Cholotl's Soul Core of War",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU291bENvcmVzL05ld1NvdWxDb3JlUHJvamVjdGlsZSIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/dfc35bed7f/NewSoulCoreProjectile.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/SoulCores/NewSoulCoreRage": {
    entry: {
      gggPath: "Metadata/Items/Currency/SoulCores/NewSoulCoreRage",
      ninjaId: "tzamotos-soul-core-of-ferocity",
      displayName: "Tzamoto's Soul Core of Ferocity",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU291bENvcmVzL05ld1NvdWxDb3JlUmFnZSIsInNjYWxlIjoxLCJyZWFsbSI6InBvZTIifV0/7bbacc1706/NewSoulCoreRage.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/SoulCores/NewSoulCoreTimeCooldown": {
    entry: {
      gggPath: "Metadata/Items/Currency/SoulCores/NewSoulCoreTimeCooldown",
      ninjaId: "quipolatls-soul-core-of-flow",
      displayName: "Quipolatl's Soul Core of Flow",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU291bENvcmVzL05ld1NvdWxDb3JlVGltZUNvb2xkb3duIiwic2NhbGUiOjEsInJlYWxtIjoicG9lMiJ9XQ/dab6d943f3/NewSoulCoreTimeCooldown.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/SoulCores/NewSoulCoreTimeSlow": {
    entry: {
      gggPath: "Metadata/Items/Currency/SoulCores/NewSoulCoreTimeSlow",
      ninjaId: "estazuntis-soul-core-of-convalescence",
      displayName: "Estazunti's Soul Core of Convalescence",
      category: "Vaal",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU291bENvcmVzL05ld1NvdWxDb3JlVGltZVNsb3ciLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/c32a5b3a47/NewSoulCoreTimeSlow.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
  "Metadata/Items/Currency/StrongboxSkeletonKey": {
    entry: {
      gggPath: "Metadata/Items/Currency/StrongboxSkeletonKey",
      ninjaId: "cryptic-key",
      displayName: "Cryptic Key",
      category: "Currency",
      iconUrl: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU3Ryb25nYm94U2tlbGV0b25LZXkiLCJzY2FsZSI6MSwicmVhbG0iOiJwb2UyIn1d/ae08d02326/StrongboxSkeletonKey.png",
      goldCostPerUnit: -1,
      mappingSource: "checked-in-verified",
      lastVerifiedUtc: "2026-08-18T00:00:00Z",
    },
    validatedRate: 0,
    observations: 0,
  },
};

export const QUARANTINED_MAPPING: Record<string, { ninjaId: string; reason: string }> = {
  "Metadata/Items/Currency/CurrencyWeaponQuality": { ninjaId: "whetstone", reason: "failed cross-validation" },
  "Metadata/Items/Currency/CurrencyUpgradeMagicToRare": { ninjaId: "regal", reason: "failed cross-validation" },
  "Metadata/Items/Currency/CurrencyUpgradeToUnique": { ninjaId: "chance", reason: "failed cross-validation" },
  "Metadata/Items/Currency/CurrencyFlaskQuality": { ninjaId: "bauble", reason: "failed cross-validation" },
  "Metadata/Items/Currency/CurrencyVaal": { ninjaId: "vaal", reason: "failed cross-validation" },
  "Metadata/Items/Currency/CurrencyRerollSocketNumbers01": { ninjaId: "lesser-jewellers-orb", reason: "failed cross-validation" },
  "Metadata/Items/Currency/CurrencyRerollSocketNumbers02": { ninjaId: "greater-jewellers-orb", reason: "failed cross-validation" },
  "Metadata/Items/Currency/CurrencyRerollSocketNumbers03": { ninjaId: "perfect-jewellers-orb", reason: "failed cross-validation" },
  "Metadata/Items/Currency/AnnullOrb": { ninjaId: "annul", reason: "failed cross-validation" },
  "Metadata/Items/Currency/FracturingOrb": { ninjaId: "fracturing-orb", reason: "failed cross-validation" },
  "Metadata/Items/Currency/StrongboxSkeletonKey": { ninjaId: "cryptic-key", reason: "failed cross-validation" },
  "Metadata/Items/Currency/CurrencyAddModToMagic2": { ninjaId: "greater-orb-of-augmentation", reason: "failed cross-validation" },
  "Metadata/Items/Currency/CurrencyUpgradeToMagic2": { ninjaId: "greater-orb-of-transmutation", reason: "failed cross-validation" },
  "Metadata/Items/Currency/CurrencyAddEquipmentSocketShard": { ninjaId: "artificers-shard", reason: "failed cross-validation" },
};