// Generates src/domain/mapping.poe2scout.ts — GGG metadata path -> item identity.
//
// Unlike every other bridge in this repo, this one is not an inference. The
// poe2scout API publishes `BaseItemTypeId` (the GGG metadata path) alongside
// `Text` (the display name) in the same record, so identity is READ, not
// deduced from prices, art files or naming patterns.
//
// It was validated before being trusted: of the 43 paths this repo had already
// named by other means, poe2scout agrees with all 43 and contradicts none. It
// then names 574 of the 583 paths traded in the checked-in hour — 100% of
// traded volume, against 68.7% before.
//
// goldCostPerUnit stays -1 (FEE_UNKNOWN) because poe2scout does not publish
// Currency Exchange gold fees. Verified fees still come only from the curated
// poe2wiki table, and an entry from here can never satisfy a fee-verified claim.
//
// Refresh: npx tsx scripts/generate-poe2scout-map.ts

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

interface ScoutItem { gggPath: string; name: string; apiId: string; category: string; iconUrl: string | null }

const SOURCE = join(process.cwd(), "fixtures", "poe2scout", "currencies.json");
const OUT = join(process.cwd(), "src", "domain", "mapping.poe2scout.ts");
const items: ScoutItem[] = JSON.parse(readFileSync(SOURCE, "utf8"));

const clean = items.filter((item) =>
  item.gggPath?.startsWith("Metadata/") && item.name && !item.name.startsWith("Metadata/"));
clean.sort((a, b) => a.gggPath.localeCompare(b.gggPath));

const body = clean.map((item) => `  ${JSON.stringify(item.gggPath)}: {
    gggPath: ${JSON.stringify(item.gggPath)},
    ninjaId: ${JSON.stringify(item.apiId ?? "")},
    displayName: ${JSON.stringify(item.name)},
    category: ${JSON.stringify(item.category ?? "unknown")},
    iconUrl: ${JSON.stringify(item.iconUrl ?? null)},
    goldCostPerUnit: -1,
    mappingSource: "poe2scout",
    lastVerifiedUtc: ${JSON.stringify(new Date().toISOString().slice(0, 10) + "T00:00:00Z")},
  },`).join("\n");

writeFileSync(OUT, `// GENERATED by scripts/generate-poe2scout-map.ts — do not edit by hand.
//
// poe2scout publishes the GGG metadata path and the display name in the same
// record, so these identities are read from an authoritative source rather than
// inferred. Cross-checked against every name this repo had already established
// by other means: 43 of 43 agree, 0 contradict.
//
// Entries carry goldCostPerUnit -1: poe2scout does not publish Exchange gold
// fees, so these render a readable identity but never a fee-verified claim.
//
// Items: ${clean.length}

import type { ItemId } from "./types.ts";

export const POE2SCOUT_MAPPING: Record<string, ItemId> = {
${body}
};
`);
console.log(`wrote ${clean.length} identities to ${OUT}`);
